// JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
<template>
  <li>
    <img :alt="product.Name" :src="product.ImageSrc"><br>
    <div>{{ product.Name }}</div>
    <DxCheckBox
      @value-changed="onValueChanged"
      text="Available"
    />
  </li>
</template>
<script>
import { DxCheckBox } from 'devextreme-vue/check-box';

export default {
  components: {
    DxCheckBox,
  },
  props: {
    product: {
      type: Object,
      required: true,
      default: () => {},
    },
  },
  methods: {
    onValueChanged(e) {
      this.$emit('checked', e, this.product);
    },
  },
};
</script>

// JSDemos/Demos/Toast/Overview/React/ProductItem.js
import React from "react";

import { CheckBox } from "devextreme-react/check-box";

export function ProductItem(props) {
  return (
    <React.Fragment>
      <img src={props.product.ImageSrc} alt="monitor" />
      <div id="name">{props.product.Name}</div>
      <CheckBox
        text="Available"
        onValueChanged={(e) => props.checkAvailability(e, props.product)}
      />
    </React.Fragment>
  );
}
