// JSDemos/Demos/Charts/WinlossSparklines/Vue/RowTemplate.vue
<template>
  <tr class="rows-content">
    <th>{{ year }}</th>
    <td>
      <DxSparkline
        :data-source="aluminumCosts"
        :show-min-max="true"
        :winloss-threshold="2100"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="winloss"
      >
        <DxTooltip format="currency"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="nickelCosts"
        :show-min-max="true"
        :show-first-last="false"
        :winloss-threshold="19000"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="winloss"
        win-color="#6babac"
        loss-color="#8076bb"
      >
        <DxTooltip format="currency"/>
      </DxSparkline>
    </td>
    <td>
      <DxSparkline
        :data-source="copperCosts"
        :winloss-threshold="8000"
        :value-field="year"
        class="sparkline"
        argument-field="month"
        type="winloss"
        first-last-color="#e55253"
        win-color="#7e4452"
        loss-color="#ebdd8f"
      >
        <DxTooltip format="currency"/>
      </DxSparkline>
    </td>
  </tr>
</template>

<script setup lang="ts">
import DxSparkline, {
  DxTooltip,
} from 'devextreme-vue/sparkline';
import {
  aluminumCosts,
  nickelCosts,
  copperCosts,
} from './data.js';

withDefaults(defineProps<{
  year?: string
}>(), {
  year: () => {},
});
</script>
<style>
.rows-content td {
  font-weight: 400;
  width: 200px;
  padding: 25px 10px 5px 10px;
  border: 1px solid #c2c2c2;
}

.rows-content tr:nth-child(2) td {
  border-top: 1px solid #c2c2c2;
}

.rows-content td:first-of-type {
  border-left: 1px solid #c2c2c2;
}

.rows-content .sparkline {
  width: 200px;
  height: 30px;
}
</style>

// JSDemos/Demos/Charts/WinlossSparklines/React/RowTemplate.tsx


interface RowTemplateProps {
key: number;
year: string;
}import React from 'react';

import Sparkline, {
  Tooltip,
} from 'devextreme-react/sparkline';

import {
  aluminumCosts,
  nickelCosts,
  copperCosts,
} from './data.ts';

export default function RowTemplate(props: RowTemplateProps) {
  return (
    <tr>
      <th>{ props.year }</th>
      <td>
        <Sparkline
          dataSource={aluminumCosts}
          showMinMax={true}
          winlossThreshold={2100}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="winloss"
        >
          <Tooltip format="currency" />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={nickelCosts}
          showMinMax={true}
          showFirstLast={false}
          winlossThreshold={19000}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="winloss"
          winColor="#6babac"
          lossColor="#8076bb"
        >
          <Tooltip format="currency" />
        </Sparkline>
      </td>
      <td>
        <Sparkline
          dataSource={copperCosts}
          winlossThreshold={8000}
          className="sparkline"
          argumentField="month"
          valueField={props.year}
          type="winloss"
          firstLastColor="#e55253"
          winColor="#7e4452"
          lossColor="#ebdd8f"
        >
          <Tooltip format="currency" />
        </Sparkline>
      </td>
    </tr>
  );
}
