// JSDemos/Demos/DataGrid/CellCustomization/Vue/ChartCell.vue
<template>
  <div class="chart-cell">
    <DxSparkline
      :data-source="dayClose"
      :show-min-max="true"
      :point-size="6"
      argument-field="date"
      value-field="close"
      type="line"
      min-color="#f00"
      max-color="#2ab71b"
    >
      <DxSize
        :width="290"
        :height="40"
      />
      <DxTooltip :enabled="false"/>
    </DxSparkline>
  </div>
</template>
<script setup lang="ts">
import {
  DxSparkline,
  DxSize,
  DxTooltip,
} from 'devextreme-vue/sparkline';

import { DayClose } from './data';

defineProps<{
  dayClose: DayClose[]
}>();
</script>

// JSDemos/Demos/DataGrid/CellCustomization/React/ChartCell.tsx
import React from 'react';
import Sparkline, { Size, Tooltip } from 'devextreme-react/sparkline';

export default function ChartCell(cellData: { data: { dayClose: any; }; }) {
  return (
    <div className="chart-cell">
      <Sparkline
        dataSource={cellData.data.dayClose}
        argumentField="date"
        valueField="close"
        type="line"
        showMinMax={true}
        minColor="#f00"
        maxColor="#2ab71b"
        pointSize={6}>
        <Size width={290} height={40} />
        <Tooltip enabled={false} />
      </Sparkline>
    </div>
  );
}
