// JSDemos/Demos/Charts/SignalRService/React/TooltipTemplate.tsx
import React from 'react';

const formatCurrency = new Intl.NumberFormat('en-US',
  { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format;

const formatNumber = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 0,
}).format;

export default function TooltipTemplate(pointInfo: { points: any[]; argumentText: any; }) {
  const volume = pointInfo.points.filter((point: { seriesName: string; }) => point.seriesName === 'Volume')[0];
  const prices = pointInfo.points.filter((point: { seriesName: string; }) => point.seriesName !== 'Volume')[0];

  return (
    <div className="tooltip-template">
      <div>{ pointInfo.argumentText }</div>
      <div><span>Open: </span>
        { formatCurrency(prices.openValue) }
      </div>
      <div><span>High: </span>
        { formatCurrency(prices.highValue) }
      </div>
      <div><span>Low: </span>
        { formatCurrency(prices.lowValue) }
      </div>
      <div><span>Close: </span>
        { formatCurrency(prices.closeValue) }
      </div>
      <div><span>Volume: </span>
        { formatNumber(volume.value) }
      </div>
    </div>
  );
}

// JSDemos/Demos/Charts/SignalRService/Vue/TooltipTemplate.vue
<template>
  <div class="tooltip-template">
    <div>{{ pointInfo.argumentText }}</div>
    <div><span>Open: </span>
      {{ formatCurrency(prices.openValue, "USD") }}
    </div>
    <div><span>High: </span>
      {{ formatCurrency(prices.highValue, "USD") }}
    </div>
    <div><span>Low: </span>
      {{ formatCurrency(prices.lowValue, "USD") }}
    </div>
    <div><span>Close: </span>
      {{ formatCurrency(prices.closeValue, "USD") }}
    </div>
    <div><span>Volume: </span>
      {{ formatNumber(volume.value, { maximumFractionDigits: 0 }) }}
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(defineProps<{
  pointInfo: Record<string, unknown>
}>(), {
  pointInfo: () => ({}),
});
const volume = computed<{value : number}>(() => props.pointInfo.points.filter(({ seriesName }) => seriesName === 'Volume')[0]);
const prices = computed<Record<string, any>>(() => props.pointInfo.points.filter(({ seriesName }) => seriesName !== 'Volume')[0]);

const formatCurrency = new Intl.NumberFormat('en-US',
  { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format;

const formatNumber = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 0,
}).format;
</script>
<style>
.tooltip-template span {
  font-weight: 500;
}
</style>
