// JSDemos/Demos/Form/CustomizeItem/React/LabelNotesTemplate.js
import React from 'react';
import { Tooltip } from 'devextreme-react/tooltip';

const LabelNotesTemplate = React.useCallback((data) => (
  <React.Fragment>
    <span>
      <i className="dx-icon dx-icon-comment"></i>
      Additional
      <br />
      <i id="helpedInfo" className="dx-icon dx-icon-info"></i>
      { data.text }
    </span>

    <Tooltip
      target="#helpedInfo"
      showEvent="mouseenter"
      hideEvent="mouseleave"
    >
      <b>This field must not exceed 200 characters</b>
    </Tooltip>
  </React.Fragment>
), []);

export default LabelNotesTemplate;

// JSDemos/Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
<template>
  <div>
    <span>
      <i class="dx-icon dx-icon-comment"/>
      Additional
      <br>
      <i
        id="helpedInfo"
        class="dx-icon dx-icon-info"
      />
      { data.text }
    </span>

    <DxTooltip
      target="#helpedInfo"
      show-event="mouseenter"
      hide-event="mouseleave"
    >
      <b>This field must not exceed 200 characters</b>
    </DxTooltip>
  </div>
</template>
<script>

import { DxTooltip } from 'devextreme-vue/tooltip';

export default {
  components: {
    DxTooltip,
  },
  props: {
    data: {
      type: Object,
      default: () => {},
    },
  },
};
