// JSDemos/Demos/Popup/Overview/React/EmployeeItem.tsx
import React from 'react';

import { Button } from 'devextreme-react/button';

export class EmployeeItem extends React.Component {
  props: any;

  showInfo: any;

  constructor(props) {
    super(props);

    this.showInfo = () => this.props.showInfo(props.employee);
  }

  render() {
    return (
      <React.Fragment>
        <img src={ this.props.employee.Picture } id={ `image${this.props.employee.ID}` } /><br />
        <i>{this.props.employee.FirstName} {this.props.employee.LastName}</i><br />
        // @ts-expect-error TS(2786): 'Button' cannot be used as a JSX component.
        <Button
          className="button-info"
          text="Details"
          onClick={this.showInfo}
        />
      </React.Fragment>
    );
  }
}

// JSDemos/Demos/Popup/Overview/Vue/EmployeeItem.vue
<template>
  <li>
    <img 
         :src="employee.Picture"
         :id="'image' + employee.ID"
    ><br>
    <i>{{ employee.FirstName }} {{ employee.LastName }}</i><br>
    <DxButton
      :on-click="showEmployeeInfo"
      class="button-info"
      text="Details"
    />
  </li>
</template>
<script>
import { DxButton } from 'devextreme-vue/button';

export default {
  components: {
    DxButton
  },

  props: {
    employee: {
      type: Object,
      required: true,
      default: () => ({})
    },
    showInfo: {
      type: Function,
      required: true,
      default: () => {}
    }
  },

  methods: {
    showEmployeeInfo() {
      this.showInfo(this.employee);
    }
  }
};
</script>
