// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Vue/AddressTab.vue
<template>
  <DxForm
    :form-data="data"
    :items="items"
    :col-count="2"
    :customize-item="customizeItem"
    class="address-form form-container"
  >
    <template #form-item="{ data: item }">
      <span>
        {{ item.editorOptions.value }}
      </span>
    </template>
  </DxForm>
</template>

<script setup lang="ts">
import { DxForm } from 'devextreme-vue/form';

defineProps<{
  data: object
}>();

const items = ['Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone'];

const customizeItem = (item) => {
  item.template = 'form-item';
}
</script>

// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/AddressTab.tsx
import React from 'react';
import { Form, Item } from 'devextreme-react/form';

const items = ['Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone'];

interface AddressTabProps {
data: any;
}

class AddressTab extends React.Component<AddressTabProps> {
  render() {
    return (
      <Form
        formData={this.props.data}
        colCount={2}
        className="address-form form-container"
      >
        {
          items.map((item, index) => <Item
            dataField={item}
            key={index}
            render={this.renderFormItem}
          />)
        }
      </Form>
    );
  }

  renderFormItem(item: { editorOptions: { value: any; }; }) {
    return <span>{item.editorOptions.value}</span>;
  }
}

export default AddressTab;
