// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Vue/ProductSelectBox.vue
<template>
  <DxSelectBox
    :defer-rendering="false"
    :data-source="dataSource"
    :input-attr="{ 'aria-label': 'Product' }"
    :value="productId"
    value-expr="ProductID"
    display-expr="ProductName"
    @valueChanged="$emit('product-changed', $event.value)"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxSelectBox from 'devextreme-vue/select-box';

import { createStore } from 'devextreme-aspnet-data-nojquery';

import { Product } from './data.ts'

defineEmits(['product-changed']);

const props = defineProps<{
  supplierId: number
}>();

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';

const dataSource = createStore({
  key: 'ProductID',
  loadParams: { SupplierID: props.supplierId },
  loadUrl: `${url}/GetProductsBySupplier`,
  onLoaded: setDefaultValue,
});

const productId = ref(null);

function setDefaultValue(items: Product[]) {
  const firstItem = items[0];

  if (firstItem && productId.value === null) {
    productId.value = firstItem.ProductID;
  }
}
</script>

// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/ProductSelectBox.tsx
import React from 'react';
import { SelectBox } from 'devextreme-react/select-box';
import { createStore } from 'devextreme-aspnet-data-nojquery';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridAdvancedMasterDetailView';
const productLabel = { 'aria-label': 'Product' };

interface ProductSelectBoxProps {
supplierId: any;
productId: any;
onProductChanged: any;
}

const ProductSelectBox = (props: ProductSelectBoxProps) => {
  const [productsData, setProductsData] = React.useState(null);

  const valueChanged = React.useCallback((e: { value: any; }) => {
    props.onProductChanged(e.value);
  }, [props]);

  React.useEffect(() => {
    const setDefaultValue = (items: any[]) => {
      const firstItem = items[0];
      if (firstItem && props.productId === null) {
        props.onProductChanged(firstItem.ProductID);
      }
    };

    const newProductsData = createStore({
      key: 'ProductID',
      loadParams: { SupplierID: props.supplierId },
      loadUrl: `${url}/GetProductsBySupplier`,
      onLoaded: setDefaultValue,
    });

    setProductsData(newProductsData);
  }, [props]);

  return (
    <SelectBox
      value={props.productId}
      deferRendering={false}
      inputAttr={productLabel}
      dataSource={productsData}
      valueExpr="ProductID"
      displayExpr="ProductName"
      onValueChanged={valueChanged}
    />
  );
};

export default ProductSelectBox;
