// JSDemos/Demos/DataGrid/CollaborativeEditing/Vue/Grid.vue
<template>
  <DxDataGrid
    :data-source="dataSource"
    :height="600"
    :show-borders="true"
    :repaint-changes-only="true"
    :highlight-changes="true"
  >
    <DxPaging
      :enabled="false"
    />

    <DxEditing
      :allow-deleting="true"
      :allow-updating="true"
      :allow-adding="true"
      :use-icons="true"
      mode="cell"
      refresh-mode="reshape"
    />

    <DxColumn
      :width="50"
      data-field="Prefix"
      caption="Title"
    >
      <DxRequiredRule/>
    </DxColumn>

    <DxColumn
      data-field="FirstName"
    >
      <DxRequiredRule/>
    </DxColumn>

    <DxColumn
      :lookup="lookup"
      data-field="StateID"
      caption="State"
    >
      <DxRequiredRule/>
    </DxColumn>

    <DxColumn
      data-field="BirthDate"
      data-type="date"
    >
      <DxRangeRule
        :max="maxDate"
        message="Date can not be greater than 01/01/3000"
      />
    </DxColumn>
  </DxDataGrid>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {
  DxDataGrid, DxColumn, DxPaging, DxEditing, DxRequiredRule, DxRangeRule,
} from 'devextreme-vue/data-grid';
import * as AspNetData from 'devextreme-aspnet-data-nojquery';

withDefaults(defineProps<{
  dataSource?: object
}>(), {
  dataSource: () => ({}),
});

const maxDate = ref(new Date(3000, 0));
const lookup = ref({
  dataSource: statesStore,
  displayExpr: 'Name',
  valueExpr: 'ID',
});
const statesStore = AspNetData.createStore({
  key: 'ID',
  loadUrl: 'https://js.devexpress.com/Demos/NetCore/api/DataGridStatesLookup',
});
</script>

// JSDemos/Demos/DataGrid/CollaborativeEditing/React/Grid.tsx
import React from 'react';
import DataGrid, {
  Column, Editing, Paging, RequiredRule, RangeRule, Lookup,
} from 'devextreme-react/data-grid';
import * as AspNetData from 'devextreme-aspnet-data-nojquery';

const maxDate = new Date(3000, 0);
const statesStore = AspNetData.createStore({
  key: 'ID',
  loadUrl: 'https://js.devexpress.com/Demos/NetCore/api/DataGridStatesLookup',
});

interface GridProps {
dataSource: CustomStore<any, any>;
}

const Grid = (props: GridProps) => (
  <DataGrid
    dataSource={props.dataSource}
    height={600}
    showBorders={true}
    repaintChangesOnly={true}
    highlightChanges={true}
  >
    <Paging
      enabled={false}
    />

    <Editing
      mode="cell"
      refreshMode="reshape"
      allowUpdating={true}
      allowDeleting={true}
      allowAdding={true}
      useIcons={true}
    />

    <Column
      dataField="Prefix"
      caption="Title"
      width={50}
    >
      <RequiredRule />
    </Column>

    <Column
      dataField="FirstName"
    >
      <RequiredRule />
    </Column>

    <Column
      dataField="StateID"
      caption="State"
    >
      <Lookup
        dataSource={statesStore}
        displayExpr="Name"
        valueExpr="ID"
      />
      <RequiredRule />
    </Column>

    <Column
      dataField="BirthDate"
      dataType="date"
    >
      <RangeRule
        max={maxDate}
        message="Date can not be greater than 01/01/3000"
      />
    </Column>

  </DataGrid>
);

export default Grid;
