// JSDemos/Demos/VectorMap/TooltipHTMLSupport/Vue/PieChart.vue
<template>
  <DxPieChart
    :data-source="data"
    :animation="false"
  >
    <DxSeries
      argument-field="name"
      value-field="value"
    >
      <DxLabel
        :visible="true"
        :customize-text="customizeText"
      >
        <DxConnector
          :visible="true"
          :width="1"
        />
      </DxLabel>
    </DxSeries>
    <DxLegend :visible="false"/>
    <DxSize
      :width="400"
      :height="200"
    />
  </DxPieChart>
</template>
<script>

import DxPieChart, {
  DxSeries,
  DxLabel,
  DxLegend,
  DxConnector
} from 'devextreme-vue/pie-chart';

export default {
  components: {
    DxPieChart,
    DxSeries,
    DxLabel,
    DxLegend,
    DxConnector,
    DxSize
  },
  props: {
    data: {
      type: Array,
      default: ()=>[]
    }
  },
  methods: {
    customizeText(pointInfo) {
      return `${pointInfo.argument[0].toUpperCase()}${
        pointInfo.argument.slice(1)
      }: $${pointInfo.value}M`;
    }
  },
};
</script>

// JSDemos/Demos/VectorMap/Overview/React/PieChartComponent.tsx
import React from 'react';
import PieChart, {
  Series,
  Label,
  Legend,
  Connector,
} from 'devextreme-react/pie-chart';

function customizeText(pointInfo: { argument: string | any[]; value: any; }) {
  return `${pointInfo.argument[0].toUpperCase()}${
    pointInfo.argument.slice(1)
  }: $${pointInfo.value}M`;
}

function PieChartComponent(props: { data: any; }) {
  return (
    <PieChart id="gdp-sectors"
      dataSource={props.data}
      animation={false}
    >
      <Series
        argumentField="name"
        valueField="value">
        <Label
          visible={true}
          customizeText={customizeText}
        >
          <Connector
            visible={true}
            width={1}
          ></Connector>
        </Label>
      </Series>
      <Legend visible={false}></Legend>
    </PieChart>
  );
}

export default PieChartComponent;
