// JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCellMonth.vue
<template>
  <DataCell
    class="dx-scheduler-date-table-cell-text"
    :cell-data="cellData"
  >
    {{ day() }}
  </DataCell>
</template>
<script setup lang="ts">
import DataCell from './DataCell.vue';

const props = withDefaults(defineProps<{
  cellData?: object
}>(), {
  cellData: () => {},
});

function day() {
  return props.cellData.startDate.getDate();
}
</script>

// JSDemos/Demos/Scheduler/CellTemplates/React/DataCellMonth.tsx
import React from 'react';
import DataCell from './DataCell.js';

const DataCellMonth = (props: { data: { startDate: any; }; }) => {
  const { startDate } = props.data;
  const day = startDate.getDate();

  return (
    <DataCell
      data={props.data}
      className='dx-scheduler-date-table-cell-text'
    >
      {day}
    </DataCell>
  );
};

export default DataCellMonth;
