// JSDemos/Demos/Scheduler/CellTemplates/Vue/TimeCell.vue
<template>
  <div :class="markTimeCell(cellData)">
    {{ cellData.text }}
    <div
      v-if="hasCoffeeCupIcon"
      class="cafe"
    />
  </div>
</template>
<script>
import Utils from './utils.js';

export default {
  props: {
    cellData: {
      type: Object,
      default: () => {}
    }
  },
  computed: {
    isDinner: function() {
      const date = this.cellData.date;
      return Utils.isDinner(date);
    },
    hasCoffeeCupIcon: function() {
      const date = this.cellData.date;
      return Utils.hasCoffeeCupIcon(date);
    },
  },
  methods: {
    markTimeCell(cellData) {
      return { 'dinner': Utils.isDinner(cellData.date) };
    }
  }
};
</script>

// JSDemos/Demos/Scheduler/CellTemplates/React/TimeCell.tsx
import React from 'react';
import Utils from './utils.js';

const TimeCell = (props: { data: { date: any; text: any; }; }) => {
  const { date, text } = props.data;

  const isDinner = Utils.isDinner(date);
  const hasCoffeeCupIcon = Utils.hasCoffeeCupIcon(date);

  return (
    <div className={isDinner ? 'dinner' : null}>
      {text}
      {hasCoffeeCupIcon ? <div className='cafe' /> : null}
    </div>
  );
};

export default TimeCell;
