// JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/NavigationList.vue
<template>
  <div>
    <DxList
      :data-source="navigation"
      :active-state-enabled="false"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      class="panel-list dx-theme-accent-as-background-color"
    />
  </div>
</template>
<script setup lang="ts">
import { DxList } from 'devextreme-vue/list';
import { navigation } from './data.js';
</script>

// JSDemos/Demos/Drawer/TopOrBottomPosition/React/NavigationList.js
import React from 'react';

import List from 'devextreme-react/list.js';
import { navigation } from './data.js';

class NavigationList extends React.PureComponent {
  render() {
    return (
      <div className="list">
        <List
          dataSource={navigation}
          height={200}
          className="panel-list dx-theme-accent-as-background-color" />
      </div>
    );
  }
}

export default NavigationList;
