// JSDemos/Demos/FilterBuilder/Customization/Vue/EditorComponent.vue
<template>
  <DxTagBox
    :value="conditionInfo.value"
    :items="categories"
    :input-attr="{ 'aria-label': 'Category' }"
    width="auto"
    @value-changed="onValueChanged"
  />
</template>

<script setup lang="ts">
import DxTagBox from 'devextreme-vue/tag-box';
import { categories } from './data';

const props = withDefaults(defineProps<{
  conditionInfo?: Record<string, any>
}>(), {
  conditionInfo: () => ({}),
});

function onValueChanged(e) {
  props.conditionInfo.setValue(e.value && e.value.length ? e.value : null);
}
</script>

// JSDemos/Demos/FilterBuilder/Customization/ReactJs/EditorComponent.js
import React from 'react';
import TagBox from 'devextreme-react/tag-box';
import { categories, categoryLabel } from './data.js';
// eslint-disable-next-line no-unused-vars
export class EditorComponent extends React.Component {
  constructor(props) {
    super(props);
    this.onValueChanged = this.onValueChanged.bind(this);
  }

  render() {
    return (
      <TagBox
        inputAttr={categoryLabel}
        defaultValue={this.props.data.value}
        items={categories}
        onValueChanged={this.onValueChanged}
        width="auto"
      />
    );
  }

  onValueChanged(e) {
    this.props.data.setValue(e.value && e.value.length ? e.value : null);
  }
}
