// JSDemos/Demos/DataGrid/Overview/React/DiscountCell.tsx
import React from 'react';

import Bullet, {
  Font, Margin, Size, Tooltip,
} from 'devextreme-react/bullet';

const customizeTooltip = (data: { value: string; }) => ({
  text: `${parseInt(data.value, 10)}%`,
});

const DiscountCell = (cellData: { value: number; }) => (
  <Bullet
    showTarget={false}
    showZeroLevel={true}
    value={cellData.value * 100}
    startScaleValue={0}
    endScaleValue={100}
  >
    <Size width={150} height={35} />
    <Margin top={5} bottom={0} left={5} />
    <Tooltip
      enabled={true}
      paddingTopBottom={2}
      zIndex={5}
      customizeTooltip={customizeTooltip}
    >
      <Font size={18} />
    </Tooltip>
  </Bullet>
);

export default DiscountCell;

// JSDemos/Demos/DataGrid/Overview/Vue/DiscountCell.vue
<template>
  <DxBullet
    :show-target="false"
    :show-zero-level="true"
    :value="cellData.value * 100"
    :start-scale-value="0"
    :end-scale-value="100"
  >
    <DxSize
      :width="150"
      :height="35"
    />
    <DxMargin
      :top="5"
      :bottom="0"
      :left="5"
    />
    <DxTooltip
      :enabled="true"
      :padding-top-bottom="2"
      :z-index="5"
      :customize-tooltip="customizeTooltip"
    >
      <DxFont :size="18"/>
    </DxTooltip>
  </DxBullet>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import {
  DxBullet,
  DxFont,
  DxMargin,
  DxSize,
  DxTooltip,
} from 'devextreme-vue/bullet';

withDefaults(defineProps<{
  cellData?: object
}>(), {
  cellData: () => {},
});

const customizeTooltip = ref((data) => {
  return {
    text: `${parseInt(data.value, 10)}%`,
  };
});
</script>
<style>
.dx-datagrid .dx-data-row > td.bullet {
  padding-top: 0;
  padding-bottom: 0;
}
</style>
