// JSDemos/Demos/Scheduler/CurrentTimeIndicator/React/AppointmentTemplate.tsx
import React from 'react';
import Query from 'devextreme/data/query';

import { moviesData } from './data.ts';

const getMovieById = (id) => Query(moviesData).filter(['id', id]).toArray()[0];

const AppointmentTemplate = (props: { data: { appointmentData: any; }; }) => {
  const { appointmentData } = props.data;

  const movieInfo = getMovieById(appointmentData.movieId) || {};

  return (
    <div className="movie">
      <img src={movieInfo.image} />
      <div className="movie-text">{movieInfo.text}</div>
    </div>
  );
};

export default AppointmentTemplate;

// JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/AppointmentTemplate.vue
<template>
  <div class="movie">
    <img :src="movieInfo.image">
    <div class="movie-text">{{ movieInfo.text }}</div>
  </div>
</template>

<script setup lang="ts">
import Query from 'devextreme/data/query';
import { moviesData } from './data.js';

const props = withDefaults(defineProps<{
  appointmentModel?: object
}>(), {
  appointmentModel: () => { },
});
const getMovieInfo = function(data) {
  return Query(moviesData)
      .filter('id', data.movieId)
      .toArray()[0] || {};
};
const movieInfo = getMovieInfo(props.appointmentModel.appointmentData);

</script>
