// JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/NavigationList.vue
<template>
  <div>
    <DxList
      :data-source="navigation"
      :active-state-enabled="false"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      class="panel-list dx-theme-accent-as-background-color"
    />
  </div>
</template>
<script setup lang="ts">
import { DxList } from 'devextreme-vue/list';
import { navigation } from './data.js';
</script>

// JSDemos/Demos/Drawer/TopOrBottomPosition/ReactJs/NavigationList.js
import React from 'react';

import List from 'devextreme-react/list';
import { navigation } from './data.js';

function NavigationList() {
  return (
    <div className="list">
      <List
        dataSource={navigation}
        className="panel-list dx-theme-accent-as-background-color"
        height={200}
      />
    </div>
  );
}
export default NavigationList;
