// JSDemos/Demos/DataGrid/CustomEditors/React/EmployeeTagBoxComponent.tsx
import React from 'react';
import TagBox from 'devextreme-react/tag-box';

const nameLabel = { 'aria-label': 'Name' };

const EmployeeTagBoxComponent = (props) => {
  const onValueChanged = React.useCallback((e: { value: any; }) => {
    props.data.setValue(e.value);
  }, [props]);

  const onSelectionChanged = React.useCallback(() => {
    props.data.component.updateDimensions();
  }, [props]);

  return (
    <TagBox
      dataSource={props.data.column.lookup.dataSource}
      defaultValue={props.data.value}
      valueExpr="ID"
      displayExpr="FullName"
      showSelectionControls={true}
      maxDisplayedTags={3}
      inputAttr={nameLabel}
      showMultiTagOnly={false}
      applyValueMode="useButtons"
      searchEnabled={true}
      onValueChanged={onValueChanged}
      onSelectionChanged={onSelectionChanged} />
  );
};

export default EmployeeTagBoxComponent;

// JSDemos/Demos/DataGrid/CustomEditors/Vue/EmployeeTagBoxComponent.vue
<template>
  <DxTagBox
    :data-source="dataSource"
    v-model:value="currentValue"
    :show-selection-controls="true"
    :input-attr="{ 'aria-label': 'Name' }"
    :max-displayed-tags="3"
    :show-multi-tag-only="false"
    :on-value-changed="(e) => onValueChanged(e.value)"
    :on-selection-changed="onSelectionChanged"
    :search-enabled="true"
    value-expr="ID"
    display-expr="FullName"
    apply-value-mode="useButtons"
  />
</template>
<script setup lang="ts">
import { ref } from 'vue';
import DxTagBox from 'devextreme-vue/tag-box';

const props = withDefaults(defineProps<{
  value?: any[]
  onValueChanged?: Function
  dataSource?: object
  dataGridComponent?: object
}>(), {
  value: () => [],
  onValueChanged: () => function() {},
  dataSource: () => {},
  dataGridComponent: () => {},
});

const currentValue = ref(props.value);

function onSelectionChanged() {
  props.dataGridComponent.updateDimensions();
};
</script>
