// JSDemos/Demos/Toast/Overview/React/ProductItem.tsx
import React from 'react';

import { CheckBox } from 'devextreme-react/check-box';

export function ProductItem(props) {
  const onValueChanged = React.useCallback((e) => {
    props.checkAvailability(e, props.product);
  }, []);

  return (
    <React.Fragment>
      <img src={props.product.ImageSrc} alt="monitor" />
      <div>{props.product.Name}</div>
      // @ts-expect-error TS(2786): 'CheckBox' cannot be used as a JSX component.
      <CheckBox
        text="Available"
        onValueChanged={onValueChanged}
      />
    </React.Fragment>
  );
}

// JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
<template>
  <li>
    <img :alt="product.Name" :src="product.ImageSrc"><br>
    <div>{{ product.Name }}</div>
    <DxCheckBox
      @value-changed="onValueChanged"
      text="Available"
    />
  </li>
</template>
<script>
import { DxCheckBox } from 'devextreme-vue/check-box';

export default {
  components: {
    DxCheckBox,
  },
  props: {
    product: {
      type: Object,
      required: true,
      default: () => {},
    },
  },
  methods: {
    onValueChanged(e) {
      this.$emit('checked', e, this.product);
    },
  },
};
</script>
