// JSDemos/Demos/DataGrid/WebAPIService/Vue/MasterDetailGrid.vue
<template>
  <DxDataGrid
    :data-source="dataSource"
    :show-borders="true"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxDataGrid from 'devextreme-vue/data-grid';
import { createStore } from 'devextreme-aspnet-data-nojquery';

const props = withDefaults(defineProps<{
  id?: number
  url?: string
}>(), {
  id: () => 0,
  url: () => '',
});

const getMasterDetailGridDataSource = (id, url) => ({
  store: createStore({
    loadUrl: `${url}/OrderDetails`,
    loadParams: { orderID: id },
    onBeforeSend: (method, ajaxOptions) => {
      ajaxOptions.xhrFields = { withCredentials: true };
    },
  }),
});
const dataSource = ref(getMasterDetailGridDataSource(props.id, props.url));

</script>

// JSDemos/Demos/DataGrid/WebAPIService/React/MasterDetailGrid.tsx
import React from 'react';
import DataGrid from 'devextreme-react/data-grid';

import { createStore } from 'devextreme-aspnet-data-nojquery';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridWebApi';

const getMasterDetailGridDataSource = (id) => ({
  store: createStore({
    loadUrl: `${url}/OrderDetails`,
    loadParams: { orderID: id },
    onBeforeSend: (method, ajaxOptions) => {
      ajaxOptions.xhrFields = { withCredentials: true };
    },
  }),
});

const MasterDetailGrid = (props: { data: { key: any; }; }) => {
  const [dataSource, setDataSource] = React.useState(null);

  React.useEffect(() => {
    const masterDetailDataSource = getMasterDetailGridDataSource(props.data.key);
    setDataSource(masterDetailDataSource);
  }, [props.data.key]);

  return (
    <DataGrid
      dataSource={dataSource}
      showBorders={true}
    />
  );
};

export default MasterDetailGrid;
