// JSDemos/Demos/List/WebAPI/React/ProductInfo.tsx
import React from 'react';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

export default function ProductInfo(item: { CategoryName: any; ProductName: any; UnitPrice: number | number | bigint; }) {
  return (
    <React.Fragment>
      <div>{item.CategoryName}</div>
      <div>{item.ProductName}</div>
      <b className="price">{currencyFormatter.format(item.UnitPrice)}</b>
    </React.Fragment>
  );
}

// JSDemos/Demos/List/WebAPI/Vue/ProductInfo.vue
<template>
  <div>
    <div>{{ item.CategoryName }}</div>
    <div>{{ item.ProductName }}</div>
    <b class="price">{{ currency(item.UnitPrice) }}</b>
  </div>
</template>
<script setup lang="ts">
withDefaults(defineProps<{
  item?: object
}>(), {
  item: () => {},
});

function currency(data) {
  return currencyFormatter.format(data);
};
const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});
</script>
