// JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.tsx


interface DateCellProps {
itemData: any;
currentView: any;
}import React from 'react';
import Utils from './utils.js';

export default function DateCell(props: DateCellProps) {
  const { currentView, date, text } = props.itemData;
  const isDisabled = currentView === 'month'
    ? Utils.isWeekend(date)
    : Utils.isDisableDate(date);

  return (
    <div className={isDisabled ? 'disable-date' : null}>
      <div>{text}</div>
    </div>
  );
}

// JSDemos/Demos/Scheduler/CellTemplates/Vue/DateCell.vue
<template>
  <div :class="markDateCell(cellData, currentView)">
    {{ cellData.text }}
  </div>
</template>
<script setup lang="ts">
import Utils from './utils.js';

withDefaults(defineProps<{
  cellData?: object
  currentView?: string
}>(), {
  cellData: () => {},
  currentView: '',
});

function markDateCell(cellData, currentView) {
  const isDisabled = currentView === 'month'
    ? Utils.isWeekend(cellData.date)
    : Utils.isDisableDate(cellData.date);
  return { 'disable-date': isDisabled };
}
</script>
