// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/OrdersTab.js
import React, { useCallback, useState } from 'react';
import { Form, Item, Label } from 'devextreme-react/form';

import ProductSelectBox from './ProductSelectBox.js';
import OrderHistory from './OrderHistory.js';

const OrdersTab = (props) => {
  const [chosenProductId, setChosenProductId] = useState(null);

  const renderSelectBox = useCallback(() => (
    <ProductSelectBox
      supplierId={props.supplierId}
      productId={chosenProductId}
      onProductChanged={setChosenProductId} />
  ), [chosenProductId, props.supplierId]);

  const renderOrderHistory = useCallback(() => (
    <OrderHistory productId={chosenProductId} />
  ), [chosenProductId]);

  return (
    <Form
      labelLocation="top"
      className="form-container"
    >
      <Item render={renderSelectBox}>
        <Label text="Product" />
      </Item>
      <Item render={renderOrderHistory}>
        <Label text="Order History" />
      </Item>
    </Form>
  );
};

export default OrdersTab;

// JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Vue/OrdersTab.vue
<template>
  <DxForm
    label-location="top"
    class="form-container"
  >
    <DxItem template="select-box">
      <DxLabel text="Product"/>
    </DxItem>
    <template #select-box>
      <ProductSelectBox
        :supplier-id="supplierId"
        @product-changed="chosenProductId = $event"
      />
    </template>

    <DxItem template="order-history">
      <DxLabel text="Order History"/>
    </DxItem>
    <template #order-history="{ data }">
      <OrderHistory
        :product-id="chosenProductId"
      />
    </template>
  </DxForm>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DxForm, DxItem, DxLabel } from 'devextreme-vue/form';
import ProductSelectBox from './ProductSelectBox.vue';
import OrderHistory from './OrderHistory.vue';

withDefaults(defineProps<{
  supplierId?: number
}>(), {
  supplierId: null,
});

const chosenProductId = ref(null);
</script>
