// JSDemos/Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
<template>
  <div>
    <span>
      <i class="dx-icon dx-icon-comment"/>
      Additional
      <br>
      <i
        id="helpedInfo"
        class="dx-icon dx-icon-info"
      />
      { data.text }
    </span>

    <DxTooltip
      target="#helpedInfo"
      show-event="mouseenter"
      hide-event="mouseleave"
    >
      <b>This field must not exceed 200 characters</b>
    </DxTooltip>
  </div>
</template>
<script>

import { DxTooltip } from 'devextreme-vue/tooltip';

export default {
  components: {
    DxTooltip,
  },
  props: {
    data: {
      type: Object,
      default: () => {},
    },
  },
};

// JSDemos/Demos/Form/CustomizeItem/React/LabelNotesTemplate.tsx
import React from 'react';
import { Tooltip } from 'devextreme-react/tooltip';

function LabelNotesTemplate(data: { text: any; }) {
  return (
    <React.Fragment>
      <div id="template-content">
        <i id="helpedInfo" className="dx-icon dx-icon-info"></i>
        Additional
        <br />
        { data.text }
      </div>

      <Tooltip
        target="#helpedInfo"
        showEvent="mouseenter"
        hideEvent="mouseleave"
      >
        <div id="tooltip-content">This field must not exceed 200 characters</div>
      </Tooltip>
    </React.Fragment>
  );
}

export default LabelNotesTemplate;
