// JSDemos/Demos/DataGrid/SignalRService/Vue/ChangeCell.vue
<template>
  <div :class="{ inc: cellData.data.change > 0, dec: cellData.data.change < 0 }">
    <span class="current-value">{{ cellData.text }}</span>
    <span class="arrow"/>
    <span class="diff">{{ cellData.data.percentChange.toFixed(2) }}%</span>
  </div>
</template>

<script setup lang="ts">
withDefaults(defineProps<{
  cellData?: object
}>(), {
  cellData: () => {},
});
</script>

// JSDemos/Demos/DataGrid/SignalRService/React/ChangeCell.tsx
import React from 'react';

export default function ChangeCell(cell: { data: { change: number; percentChange: number; }; text: any; }) {
  return (
    <div className={cell.data.change > 0 ? 'inc' : 'dec' }>
      <span className="current-value">{cell.text}</span>
      <span className="arrow"></span>
      <span className="diff">{cell.data.percentChange.toFixed(2)}%</span>
    </div>
  );
}
